---
# tasks file for deploy_apache_web
- block: #=======<REDHAT>======
  - name: Install Apache for RedHat 
    yum: name=httpd state=latest  
  - name: Start Apache service and enable on every boot 
    service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- block: #=======<DEBIAN>======  
  - name: Install Apache for Debian
    apt: name=apache2 state=present
  - name: Start Apache service and enable on every Debian boot 
    service: name=apache2 state=started enabled=yes 
  when: ansible_os_family == "Debian"

- name: Copy HomePage file page to webserver
  copy: src={{ item }} dest={{ destin_file }} mode=0555
  loop:
    - fon.jpg
    - mta-98-365.jpg
    - mta-98-366.jpg
    - mta-98-367.jpg
    - LPI_Essentials.png
    - index.html
  notify: 
    - Restart Apache RedHat
    - Restart Apache Debian