Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox"

    config.vm.define "tomcat" do |tomcat|
        tomcat.vm.provision "file", source: "4.0-tomcat-setup.sh",
            destination: "/home/vagrant/tomcat.sh"
    end

end
