Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox"

    config.vm.define "tomcat" do |tomcat|
        tomcat.vm.provision "file", source: "4.0-tomcat-setup.sh",
            destination: "/home/vagrant/tomcat/tomcat.sh"
        tomcat.vm.provision "file", source: "apache-tomcat-9.0.58.tar.gz",
            destination: "/home/vagrant/tomcat/apache-tomcat-9.0.58.tar.gz"
        tomcat.vm.provision "file", source: "server.xml",
            destination: "/home/vagrant/tomcat/server.xml"
        tomcat.vm.provision "file", source: "tomcat-users.xml",
            destination: "/home/vagrant/tomcat/tomcat-users.xml"
        tomcat.vm.provision "file", source: "tomcat.linux.jks",
            destination: "/home/vagrant/tomcat/tomcat.linux.jks"
        tomcat.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
        tomcat.vm.network "forwarded_port", guest: 8443, host: 8443, host_ip: "127.0.0.1"
    end

end
