Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox"

    config.vm.define "lemp" do |web|
        lemp.vm.provision "file", source: "3.0-lemp-setup.sh",
            destination: "/home/vagrant/tomcat.sh"
    end

end