---
- name: Install Apache and download my website
  hosts: all
  become: yes

  vars: 
    source_file: ./mysite/index.html
    source_adds: ./mysite/images
    destin_file: /var/www/html

  tasks:
  - name: Install Apache
    yum: name=httpd state=latest

  - name: Copy my website
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555 
    copy: src={{ source_adds }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Apache service and enable on every boot
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

  