---
- hosts: all
  become: true
  become_user: root
  tasks:
    - block:  #=====Block for Debian===
        - name: Debian/Ubuntu - Update apt repo and cache 
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

        - name: Debian/Ubuntu - Update all packages to their latest version
          apt: name="*" state=latest
          
        - name: Debian/Ubuntu - Upgrade all packages on servers
          apt: upgrade=dist force_apt_get=yes
        
        - name: Debian/Ubuntu - Install soft
          apt:  
          
      when: ansible_os_family == "Debian"

    - block: #=====Block for RedHat===
        - name: RedHat/CentOS - update repos
          yum: update_cache=yes 

        - name: RedHat/CentOS - upgrade repos
          yum: name='*' state=latest  

        - name: RedHat/CentOS - Install soft
          yum: 
      when: ansible_os_family == "RedHat"