---
- hosts: all
  become: true
  become_user: root
  tasks:
    - block:  #=====Block for Debian===
        - name: Update apt repo and cache on all Debian/Ubuntu boxes
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

        - name: Update all packages to their latest version
          apt: name="*" state=latest
          
        - name: Upgrade all packages on servers
          apt: upgrade=dist force_apt_get=yes

      when: ansible_os_family == "Debian"

    - block: #=====Block for RedHat===
        - name: Update RedHat/CetnOS repos
          yum: update_cache=yes 

        - name: Upgrade RedHat/CetnOS repos
          yum: name='*' state=latest  
      when: ansible_os_family == "RedHat"